# Generated by Django 6.0 on 2026-09-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0042_group_invitation_token_and_dispatch"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingDailyCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                ("event", models.CharField(max_length=32)),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("day", "event"), name="unique_onboarding_daily_event"
                    )
                ],
            },
        ),
    ]
