# Generated by Django 6.0 on 2026-09-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0044_repair_managed_members"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthThrottleEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_hash", models.CharField(db_index=True, max_length=64)),
                ("action", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
