# Generated by Django 6.0 on 2026-09-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("gifts", "0045_auththrottleevent"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("onboarding_completed_at__isnull", False),
                        ("onboarding_version__gte", 1),
                    ),
                    models.Q(
                        ("onboarding_completed_at__isnull", True),
                        ("onboarding_version", 0),
                    ),
                    _connector="OR",
                ),
                name="onboarding_completed_iff_versioned",
            ),
        ),
    ]
