# Generated by Django 6.0 on 2026-09-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0046_user_onboarding_completed_iff_versioned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auththrottleevent",
            name="ip_hash",
            field=models.CharField(max_length=64),
        ),
        migrations.AddIndex(
            model_name="auththrottleevent",
            index=models.Index(
                fields=["action", "ip_hash", "created_at"],
                name="gifts_autht_action_8f0d49_idx",
            ),
        ),
    ]
