# Generated by Django 6.0 on 2026-09-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0047_auththrottleevent_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dashboard_simple_mode",
            field=models.BooleanField(default=False),
        ),
    ]
