"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
import tomllib
from pathlib import Path

import dj_database_url
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

with (BASE_DIR / "pyproject.toml").open("rb") as pyproject_file:
    PROJECT_VERSION = tomllib.load(pyproject_file)["project"]["version"]

APP_VERSION = os.environ.get("APP_VERSION", PROJECT_VERSION)
DEPLOYMENT_REVISION = os.environ.get("DEPLOYMENT_REVISION", "")[:100]
RELEASE_NOTES_DIR = BASE_DIR / "gifts" / "release_notes"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "DEFAULT_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEV", "False") == "True"

ALLOWED_HOSTS = ["noscadeaux.fr", "www.noscadeaux.fr", "127.0.0.1", "localhost"]
PUBLIC_BASE_URL = os.environ.get("PUBLIC_BASE_URL", "https://noscadeaux.fr")

# Public bug reports are sent directly to GitHub. No report is stored by Django.
BUG_REPORT_REPOSITORY = os.environ.get("BUG_REPORT_REPOSITORY", "")
BUG_REPORT_TOKEN = os.environ.get("BUG_REPORT_TOKEN", "")
BUG_REPORT_LABELS = [
    label.strip()
    for label in os.environ.get(
        "BUG_REPORT_LABELS",
        "bug,source:user-report,status:unconfirmed",
    ).split(",")
    if label.strip()
]
GITHUB_API_URL = os.environ.get("GITHUB_API_URL", "https://api.github.com")
GITHUB_API_VERSION = os.environ.get("GITHUB_API_VERSION", "2022-11-28")
BUG_REPORT_TIMEOUT = float(os.environ.get("BUG_REPORT_TIMEOUT", "10"))

# Cloudflare Turnstile protects account creation when a secret key is configured.
# The site key is public; the secret key must only be provided to the backend.
TURNSTILE_SITE_KEY = os.environ.get("TURNSTILE_SITE_KEY", "")
TURNSTILE_SECRET_KEY = os.environ.get("TURNSTILE_SECRET_KEY", "")
TURNSTILE_ENABLED = bool(TURNSTILE_SECRET_KEY)
TURNSTILE_VERIFY_URL = "https://challenges.cloudflare.com/turnstile/v0/siteverify"
TURNSTILE_TIMEOUT = float(os.environ.get("TURNSTILE_TIMEOUT", "5"))

# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "gifts",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "anymail",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "gifts.middleware.AccountSetupMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "gifts.context_processors.application_version",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "fr"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ("fr", _("French")),
    ("en", _("English")),
]

LOCALE_PATHS = [
    BASE_DIR / "locale",
]
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "gifts" / "static",
]

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if "test" in sys.argv
            else "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"
        ),
    },
}
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
X_FRAME_OPTIONS = "DENY"

SESSION_COOKIE_AGE = 60 * 60 * 24 * 30
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
DEMO_RESET_INTERVAL_MINUTES = int(os.environ.get("DEMO_RESET_INTERVAL_MINUTES", "15"))

LOGIN_REDIRECT_URL = "dashboard"
LOGOUT_REDIRECT_URL = "welcome"
LOGIN_URL = "login"

AUTH_USER_MODEL = "gifts.User"
AUTHENTICATION_BACKENDS = [
    "gifts.backends.CaseInsensitiveModelBackend",
    "django.contrib.auth.backends.ModelBackend",
]

EMAIL_BACKEND = "anymail.backends.resend.EmailBackend"

ANYMAIL = {
    "RESEND_API_KEY": os.environ.get("ANYMAIL_RESEND_API_KEY"),
}

DEFAULT_FROM_EMAIL = "Nos Cadeaux <noreply@noscadeaux.fr>"
VERIFICATION_EMAIL_RESEND_COOLDOWN_SECONDS = 60
GROUP_INVITATION_MAX_RECIPIENTS_PER_REQUEST = int(os.environ.get("GROUP_INVITATION_MAX_RECIPIENTS_PER_REQUEST", "10"))
GROUP_INVITATION_MAX_RECIPIENTS_PER_USER_WINDOW = int(
    os.environ.get("GROUP_INVITATION_MAX_RECIPIENTS_PER_USER_WINDOW", "30")
)
GROUP_INVITATION_MAX_RECIPIENTS_PER_GROUP_WINDOW = int(
    os.environ.get("GROUP_INVITATION_MAX_RECIPIENTS_PER_GROUP_WINDOW", "100")
)
GROUP_INVITATION_RATE_WINDOW_SECONDS = int(os.environ.get("GROUP_INVITATION_RATE_WINDOW_SECONDS", "3600"))

# Per-IP throttle for account creation and verification resends (sliding window).
AUTH_RATE_WINDOW_SECONDS = int(os.environ.get("AUTH_RATE_WINDOW_SECONDS", "900"))
REGISTRATION_MAX_ATTEMPTS_PER_IP_WINDOW = int(os.environ.get("REGISTRATION_MAX_ATTEMPTS_PER_IP_WINDOW", "10"))
VERIFICATION_RESEND_MAX_ATTEMPTS_PER_IP_WINDOW = int(
    os.environ.get("VERIFICATION_RESEND_MAX_ATTEMPTS_PER_IP_WINDOW", "10")
)

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

CSRF_TRUSTED_ORIGINS = ["https://noscadeaux.fr", "https://www.noscadeaux.fr"]

SECURE_SSL_REDIRECT = not DEBUG and "test" not in sys.argv

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

UNFOLD = {
    "SITE_TITLE": "nosCadeaux Admin",
    "SITE_HEADER": "nosCadeaux",
    "SITE_SYMBOL": "redeem",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "COLORS": {
        "font": {
            "subtle-light": "107 114 128",
            "subtle-dark": "156 163 175",
            "default-light": "75 85 99",
            "default-dark": "209 213 219",
            "important-light": "17 24 39",
            "important-dark": "243 244 246",
        },
        "primary": {
            "50": "255 241 242",
            "100": "255 228 230",
            "200": "254 205 211",
            "300": "253 164 175",
            "400": "251 113 133",
            "500": "244 63 94",
            "600": "225 29 72",
            "700": "190 18 60",
            "800": "159 18 57",
            "900": "136 19 55",
            "950": "76 5 25",
        },
    },
}
